// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA92TKfx9laKndRLpbSt4rkLXlUzF0T2Lw',
    appId: '1:904970774154:web:97a8bd750c4939a0d56f73',
    messagingSenderId: '904970774154',
    projectId: 'pos-system-47f93',
    authDomain: 'pos-system-47f93.firebaseapp.com',
    databaseURL: 'https://pos-system-47f93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pos-system-47f93.appspot.com',
    measurementId: 'G-EKP16Y4LCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi7bzpU4d2mA9mns_91IveIItDd2sEjHA',
    appId: '1:904970774154:android:a2628acf5cf5cbbed56f73',
    messagingSenderId: '904970774154',
    projectId: 'pos-system-47f93',
    databaseURL: 'https://pos-system-47f93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pos-system-47f93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMSV9CRYCZtNErVlY1r6GQMII-2xwC1xU',
    appId: '1:904970774154:ios:7d53185a4b0d1591d56f73',
    messagingSenderId: '904970774154',
    projectId: 'pos-system-47f93',
    databaseURL: 'https://pos-system-47f93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pos-system-47f93.appspot.com',
    iosBundleId: 'com.reso.deercoffee.deerCoffee',
  );
}
